# numpy operations

In [2]:
import numpy as np

In [3]:
# one dimesion array
a=np.array([1,3,4,6],dtype="int32")
print(a)

[1 3 4 6]


In [4]:
# 2 dimesion array
b=np.array([[12,3,2,5,6],[5,3,5,3,4]])
print(b)

[[12  3  2  5  6]
 [ 5  3  5  3  4]]


In [5]:
# get dimension
a.ndim
b.ndim

2

In [6]:
# get shape of array (row,column)
b.shape

(2, 5)

In [7]:
# data type array
b.dtype

dtype('int32')

In [8]:
# Length of one array element in bytes.
a.itemsize

4

In [9]:
# we can also define datatype
a=np.array([1,3,4],dtype="int64")
print(a)
# changing the datatype int32 to int64 so  
a.itemsize

[1 3 4]


8

In [10]:
np.size(a)

3

In [11]:
# get total size
a.size  * a.itemsize
# other attribute
a.nbytes

24

#### Accessing / Changing specific elements rows/column

In [12]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
# get Specific elements [r,c]
a[1,4]

12

In [13]:
# get Specific Row / Column
# row
a[0,:]
# column
a[:,[1,2]]

array([[ 2,  3],
       [ 9, 10]])

In [14]:
# getting little more fancy row 0  column 1 - -1  and step 2
a[0,1:-1:2]

array([2, 4, 6])

In [15]:
# Changing and intilizing element
a[0,4] = 20
a
a[0,1:3] = [15,23]
a

array([[ 1, 15, 23,  4, 20,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

#### 3-Dimension Array

In [16]:
b= np.array([[[1,2],[3,4],[5,6],[7,8],[9,10],[11,12]],
            [[15,16],[17,18],[19,20],[21,22],[23,24],[25,26]]
            ])
b

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[15, 16],
        [17, 18],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26]]])

In [17]:
# get Specific element
b[1,3,1]

22

In [18]:
b[:,1,:]

array([[ 3,  4],
       [17, 18]])

In [19]:
# replace first 0 row then 1 row in position 1 
b[:,1,:] = [[9,9],[8,8]]
b

array([[[ 1,  2],
        [ 9,  9],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10],
        [11, 12]],

       [[15, 16],
        [ 8,  8],
        [19, 20],
        [21, 22],
        [23, 24],
        [25, 26]]])

#### initilizing different types of array

In [20]:
# all 0s Matrix
np.zeros((2,3,3))
np.zeros((1,3,2,2))

array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]])

In [21]:
# all 1s Matrix
np.ones((4,2,2))

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [37]:
# any other parameter Excepting 0 & 1
np.full((3,3,2),99)

array([[[99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99]],

       [[99, 99],
        [99, 99],
        [99, 99]]])

In [23]:
# any other number
np.full_like(b,4)

array([[[4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4]],

       [[4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4],
        [4, 4]]])

In [24]:
np.full(b.shape,2)

array([[[2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2]],

       [[2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2],
        [2, 2]]])

In [25]:
# random decimal number 3-D array its give output between 0-1 
np.random.rand(4,2,3)

array([[[0.61587084, 0.92630489, 0.31520015],
        [0.73137329, 0.24493418, 0.85739447]],

       [[0.05056945, 0.58215277, 0.1622376 ],
        [0.08478666, 0.26918357, 0.14112312]],

       [[0.50391654, 0.74291807, 0.75080949],
        [0.15704953, 0.31923528, 0.94201695]],

       [[0.42633391, 0.74913447, 0.0791686 ],
        [0.10728004, 0.49803084, 0.0638666 ]]])

In [26]:
np.random.random_sample((2,3))

array([[0.02043944, 0.36115683, 0.43243619],
       [0.46219473, 0.9043715 , 0.95432237]])

In [27]:
# 2 to 10  between 3*3 matrix
np.random.randint(2,10,size=(3,3))

array([[7, 2, 6],
       [4, 3, 4],
       [7, 2, 9]])

In [28]:
# identity matrix 3 * 3
np.identity(3,int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [29]:
# repeat one array multiple times
arr  = np.array([1,2,3])
r1 = np.repeat(arr,3,axis=0)
r1

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [30]:
#assignment

x=np.ones((5,5),dtype="int32")
y = np.zeros((3,3),dtype="int")
y[1,1] = 9
x[1:4,1:4] = y
x

array([[1, 1, 1, 1, 1],
       [1, 0, 0, 0, 1],
       [1, 0, 9, 0, 1],
       [1, 0, 0, 0, 1],
       [1, 1, 1, 1, 1]])

In [31]:
# copy
a = np.array([1,2,4])
b=a.copy()
# b = a  using assign we can not do copy for that we have to use method copy()
b[0] = 5
print(b)
print(a)

[5 2 4]
[1 2 4]


### Mathmatics

In [32]:
x=np.array([1,2,3])
y=np.array([1,2,3])
x.max()
x.min()
x.sum()
x+y
x ** 2
x * y
np.sin(x)
np.cos(y)

array([ 0.54030231, -0.41614684, -0.9899925 ])

In [33]:
# Linear Algebra in 2,3 == 3,2 same both side
a = np.ones((2,3))
b = np.full((3,2),2)
# matrix multiplication
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])